fix(local_base): fix local_base mode sql dump command

diff --git a/sitesync b/sitesync
--- a/sitesync
+++ b/sitesync
@@ -1,5 +1,20 @@
 #!/usr/bin/env bash
 
+#set -e -o pipefail -o errtrace -o functrace
+#trap 'err_handler $?' ERR
+#
+#err_handler() {
+#    trap - ERR
+#    let i=0 exit_status=$1
+#    echo -ne "\033[0;31m"
+#    echo
+#    echo "Aborting on error $exit_status:"
+#    echo "--------------------"
+#    while caller $i; do ((++i)); done
+#    echo -ne "\033[0m"
+#    exit $?
+#}
+
 # TODO: chercher-remplacer basés sur des tableaux utilisables pour les URL, les chemins, les noms d'hôtes...
 # TODO: synchronisation de dossiers basée sur des tableaux
 declare -a replace_src
@@ -244,7 +259,7 @@ then
             MSG="1/6 : dump de la base (locale)";
             printf "\r`tput el`%s" "$MSG" | tee -a $logfile
             echo "DROP DATABASE IF EXISTS \`$dst_dbname\`; CREATE DATABASE \`$dst_dbname\`; USE \`$dst_dbname\`; " > $sqlfile_tmp && \
-                ($dst_path_to_mysqldump --opt --no-data --no-create-db $sql_options_structure $arg_connexion_src $src_dbname && $dst_path_to_mysqldump --opt --no-create-db --no-create-info $sql_options $sql_ignores $arg_connexion_src $src_dbname) \
+                (sh -c "$dst_path_to_mysqldump --opt --no-data --no-create-db $sql_options_structure $arg_connexion_src $src_dbname && $dst_path_to_mysqldump --opt --no-create-db --no-create-info $sql_options $sql_ignores $arg_connexion_src $src_dbname") \
                 >> $sqlfile_tmp && mv -f $sqlfile_tmp $sqlfile
             RECUP_KO=$?
             ;;
